frase = 'curso em video python'
print(len(frase))
print(frase.count('o'))
print(frase.count('o',0,13))
print(frase[9:13:2])
print(frase.find('pyt'))
# começou na posição 15
print(frase.find('vadia'))
print('curso' in frase)
print(frase.replace('curso', 'pirocada'))
print(frase.replace(' ', '-'))
print(frase.capitalize())
print(frase.upper())
print(frase.lower())
print(frase.split())
print('°'.join(frase))
print(frase.title())
frase1 ='   Aprenda Python  '
print(frase1.strip())
print(frase1.lstrip())
print(frase1.rstrip())
print(frase.split('python'))
print(frase.split('thon'))
print(frase.split(' '))
print(frase.join(['Python', 'Java']))
